modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId="entitymod" #mandatory
version="1.0" #mandatory
displayName="Entity Mod" #mandatory
credits="Thanks for this mod goes to BainHero" #optional
authors="BainHero" #optional
description='''

'''
[[dependencies.entitymod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.entitymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
